### PR TITLE
bump hashed_key max_length from 100 to 150

### LINKED ISSUE #192: APIKey.create_key doesn't work with argon2-cffi hasher because the hasher returns strings that are more than 100 chars
**Describe the bug**
When using the hasher [argon2-cffi](https://pypi.org/project/argon2-cffi/21.2.0/), we have an error because hashed_key from AbstractAPIKey has a limit of 100 chars. argon2 can create hashes of more than that.

**To Reproduce**
1. Use argon2 as a password hasher: https://docs.djangoproject.com/fr/2.2/topics/auth/passwords/#using-argon2-with-django
2. Call `APIKey.objects.create_key(name="my-remote-service")`
3. See error

**Expected behavior**
Can create key

**Screenshots**
https://imgur.com/a/8VBFjUS

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: 0.2.1
 - Python Version: 3.8
 - Django Version: 4.0
 - DRF Version: 3.8

**Additional context**
 - argon2-cffi Version: 21.3.0

### PR DESCRIPTION
**Pull request by mariot**
Fix #192

### CODE REVIEW

**Comment by mariot** [comment]
@florimondmanca Hi, thanks a lot for looking at this! I made the changes

**Comment by florimondmanca** [comment]
@mariot Thanks

I see that we already have a test here: https://github.com/florimondmanca/djangorestframework-api-key/blob/c121bfd239c13bece678042df942676161ac6463/tests/test_permissions.py#L28-L31 that should be testing the creation of API keys with each password hasher in [PASSWORD_HASHERS](https://github.com/django/django/blob/dc9deea8e85641695e489e43ed5d5638134c15c7/django/conf/global_settings.py#L524-L530), which already contains argon2 and bcrypt among other hashers.

I'm wondering why this test still allows you to see the issue in #192. According to #192, these tests should be failing because of a `max_length` requirement failure, right?

**Comment by florimondmanca** [comment]
Hi @mariot,

Apologies for the delay on moving this forward.

I merged a recent PR #195. There, I saw CI failing on the `py38_postgres` job with an error about ID lengths. I see the same error on `master` now. This branch is passing so I am assuming this fixes the issue, as expected, i.e. the argon2 / scrypt hasher is indeed used in tests (see my previous comment) and bumping up the ID length makes them pass.

So, I'll be merging this now. We'd then need to release the changes, based on the diff here https://github.com/florimondmanca/djangorestframework-api-key/compare/2.1.0...master

We have documentation on how to prepare a release PR here: https://github.com/florimondmanca/djangorestframework-api-key/blob/master/CONTRIBUTING.md#releasing

Would you like to help out? I don't have much time to dedicate to this project anymore unfortunately, so I'd be very pleased to guide anyone into at least releasing the changes we've got in the pipeline (this PR + some "official version support" changes in #189).

**Review by florimondmanca — APPROVED** [review]

**Comment by mariot** [comment]
Hello @florimondmanca,

Thanks a lot for taking a look into this! I really appreciate it.
Yes, I can help out for the release, I'll open the release PR.

Thanks again,
Mariot.

Le mer. 2 mars 2022 à 22:10, Florimond Manca ***@***.***> a
écrit :

**Comment by chrismaddalena** [comment]
Hi @florimondmanca and @mariot! I submitted PR #196 to propose a release with these changes. I hope I'm not stepping on toes by doing so. I had the time to run through the checklists and assemble the CHANGELOG and wanted to offer assistance where I could.

**Comment by mariot** [comment]
Thanks for taking over, @chrismaddalena

**Pull request merged**
