### PR TITLE
Single-header authorization scheme

### LINKED ISSUE #16: Authentication with DRF_API_KEY_SECRET_KEY_HEADER only
**Is your feature request related to a problem? Please describe.**
It would be handy to allow client to use only a secret key value `DRF_API_KEY_SECRET_KEY_HEADER` to access endpoints.

**Describe the solution you'd like**
Client software provides only `DRF_API_KEY_SECRET_KEY_HEADER` and has its access to the endpoints and it is clear on the Django side to which client this key belongs to.

**Describe alternatives you've considered**
Adopt [DRF token authentication](https://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication) for non-human clients.

### PR DESCRIPTION
**Pull request by florimondmanca**
Fixes #16 

Changes:

- **BREAKING**: change from double-header (token/secret key) mechanism to a single-header mechanism: `Authorization: Api-Key ********`.
- The API key `********` consists of two parts (which end users don't need to care about): a prefix and a secret key. The prefix is used to retrieve the one API key that should be checked, and is displayed in the admin site for reference.
- A name must be defined to identify API keys on the admin side, but it is not used to authorize requests and doesn't need to be unique.
- Remove settings made obsolete by the above change.
- Use Django password helpers to guarantee maximum security when hashing and storing generated keys.
- **BREAKING**: regenerate migrations. Will need to add an upgrade guide for existing users.
- Migrate all tests to pytest.
- Update README.

TODO:

- [ ] Update changelog.

### CODE REVIEW

**Comment by florimondmanca** [comment]
@ssrebelious PR updated based on our latest discussions in #16. I believe this will be the final attempt as I think we've laid out a rather satisfying approach. There are a lot of changes, but feel free to go through the [new README](https://github.com/florimondmanca/djangorestframework-api-key/blob/8dfc65ea03d4111a7b598e73c891893e3e834058/README.md)! :+1: (FYI screenshots won't show up yet because they're linked to `master`.)

**Comment by ssrebelious** [comment]
Great! Waiting for release)))

**Comment by florimondmanca** [comment]
Thanks @ssrebelious. I had one question related to migration from 0.x to 1.x — have you already thought about how to handle that? I mean, API keys are fundamentally different in each versions and I don't think there's a way to convert old API keys to new ones. So you'd need erase all existing API keys (by running `migrate rest_framework_api_key zero` and then migrating again), and recreate an API key for each existing client. Are you okay with this idea?

**Comment by ssrebelious** [comment]
>  So you'd need erase all existing API keys (by running migrate rest_framework_api_key zero and then migrating again), and recreate an API key for each existing client. Are you okay with this idea?

From the beginning I had a hope that there will be a migration inside the library, but I'm OK with deleting old tables and creating new.

**Comment by florimondmanca** [comment]
I will merge this and make the custom header fix later. :+1:

**Pull request merged**
