### PR TITLE
Fix migration 0004 when run against a non default database (updated)

### PR DESCRIPTION
**Pull request by florimondmanca**
This is an update of #185 (which now has conflicts with `master` that can't be solved via the GitHub UI).

> We are using this library on a project that is running tests with a separate test database. Previously due to the missing using statement it would instead try to apply the populate_prefix_hashed_key using the default database connection.

### CODE REVIEW

**Comment by florimondmanca** [comment]
And… It's finally in. Thanks a lot @niall-mediasuite for putting time into this. I'll add this in the release batch for 2.3.0.

**Comment by niall-mediasuite** [comment]
Thanks @florimondmanca

**Comment by niall-mediasuite** [comment]
Hi @florimondmanca it doesn't look like this has been release yet. Is it possible to create a new `2.3.0` release or at least a patch for `2.2.0`?

**Comment by florimondmanca** [comment]
@niall-mediasuite Good call. I think we can release `2.3.0` as-is. We've got #210 which is in the "Removed" category, though not keen on being pedantic about semver and issuing 3.0.0 because of Python 3.6 EOL.

**Comment by niall-mediasuite** [comment]
Great, thanks. We had been pulling the library from git but it was beginning to cause issues.

**Pull request merged**
